nTests = 4;
testConfig = { 'configTest001.m', ...
               'configTest002.m', ...
               'configTest003.m', ...
               'configTest004.m', ...
               };
testDesc = {'Whole eruption, landscape', ...
            'Whole eruption, square', ...
            'Whole eruption, portrait', ...
            'Whole eruption, wide', ...
            };


for iTest = 1:nTests

    fprintf( "%3d    %s    %s\n", ...
        iTest, ...
        testConfig{iTest}, ...
        testDesc{iTest} );

    plotMegaplot( testConfig{iTest} );

end



